# coding: utf-8

"""
    Knetik Platform API Documentation latest 

    This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com

    OpenAPI spec version: latest 
    Contact: support@knetik.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.store_shopping_carts_api import StoreShoppingCartsApi


class TestStoreShoppingCartsApi(unittest.TestCase):
    """ StoreShoppingCartsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.store_shopping_carts_api.StoreShoppingCartsApi()

    def tearDown(self):
        pass

    def test_add_discount_to_cart(self):
        """
        Test case for add_discount_to_cart

        Adds a discount coupon to the cart
        """
        pass

    def test_add_item_to_cart(self):
        """
        Test case for add_item_to_cart

        Add an item to the cart
        """
        pass

    def test_create_cart(self):
        """
        Test case for create_cart

        Create a cart
        """
        pass

    def test_get_cart(self):
        """
        Test case for get_cart

        Returns the cart with the given GUID
        """
        pass

    def test_get_carts(self):
        """
        Test case for get_carts

        Get a list of carts
        """
        pass

    def test_get_countries(self):
        """
        Test case for get_countries

        Get the list of available shipping countries per vendor
        """
        pass

    def test_get_shippable(self):
        """
        Test case for get_shippable

        Returns whether a cart requires shipping
        """
        pass

    def test_remove_discount_from_cart(self):
        """
        Test case for remove_discount_from_cart

        Removes a discount coupon from the cart
        """
        pass

    def test_set_cart_currency(self):
        """
        Test case for set_cart_currency

        Sets the currency to use for the cart
        """
        pass

    def test_set_cart_owner(self):
        """
        Test case for set_cart_owner

        Sets the owner of a cart if none is set already
        """
        pass

    def test_update_item_in_cart(self):
        """
        Test case for update_item_in_cart

        Changes the quantity of an item already in the cart
        """
        pass

    def test_update_shipping_address(self):
        """
        Test case for update_shipping_address

        Modifies or sets the order shipping address
        """
        pass


if __name__ == '__main__':
    unittest.main()
