# coding: utf-8

"""
    Knetik Platform API Documentation Latest

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: Latest
    Contact: support@knetik.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.saved_address_resource import SavedAddressResource


class TestSavedAddressResource(unittest.TestCase):
    """ SavedAddressResource unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSavedAddressResource(self):
        """
        Test SavedAddressResource
        """
        model = swagger_client.models.saved_address_resource.SavedAddressResource()


if __name__ == '__main__':
    unittest.main()
