# coding: utf-8

"""
    Knetik Platform API Documentation Latest

    This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com

    OpenAPI spec version: Latest
    Contact: support@knetik.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.bre_rule_engine_categories_api import BRERuleEngineCategoriesApi


class TestBRERuleEngineCategoriesApi(unittest.TestCase):
    """ BRERuleEngineCategoriesApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.bre_rule_engine_categories_api.BRERuleEngineCategoriesApi()

    def tearDown(self):
        pass

    def test_create_template_using_post1(self):
        """
        Test case for create_template_using_post1

        Create a BRE category template
        """
        pass

    def test_delete_template_using_delete(self):
        """
        Test case for delete_template_using_delete

        Delete a BRE category template
        """
        pass

    def test_get_categories_using_get(self):
        """
        Test case for get_categories_using_get

        List categories
        """
        pass

    def test_get_category_using_get(self):
        """
        Test case for get_category_using_get

        Get a single category
        """
        pass

    def test_get_template_using_get(self):
        """
        Test case for get_template_using_get

        Get a single BRE category template
        """
        pass

    def test_get_templates_using_get(self):
        """
        Test case for get_templates_using_get

        List and search BRE category templates
        """
        pass

    def test_update_category_using_put(self):
        """
        Test case for update_category_using_put

        Update a category
        """
        pass

    def test_update_template_using_put1(self):
        """
        Test case for update_template_using_put1

        Update a BRE category template
        """
        pass


if __name__ == '__main__':
    unittest.main()
