# coding: utf-8

"""
    Knetik Platform API Documentation latest 

    This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com

    OpenAPI spec version: latest 
    Contact: support@knetik.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.challenge_event_participant_resource import ChallengeEventParticipantResource


class TestChallengeEventParticipantResource(unittest.TestCase):
    """ ChallengeEventParticipantResource unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChallengeEventParticipantResource(self):
        """
        Test ChallengeEventParticipantResource
        """
        model = swagger_client.models.challenge_event_participant_resource.ChallengeEventParticipantResource()


if __name__ == '__main__':
    unittest.main()
