# coding: utf-8

"""
    Knetik Platform API Documentation latest 

    This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com

    OpenAPI spec version: latest 
    Contact: support@knetik.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.auth_permissions_api import AuthPermissionsApi


class TestAuthPermissionsApi(unittest.TestCase):
    """ AuthPermissionsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.auth_permissions_api.AuthPermissionsApi()

    def tearDown(self):
        pass

    def test_create_permission(self):
        """
        Test case for create_permission

        Create a new permission
        """
        pass

    def test_delete_permission(self):
        """
        Test case for delete_permission

        Delete a permission
        """
        pass

    def test_get_permission(self):
        """
        Test case for get_permission

        Get a single permission
        """
        pass

    def test_get_permissions(self):
        """
        Test case for get_permissions

        List and search permissions
        """
        pass

    def test_update_permission(self):
        """
        Test case for update_permission

        Update a permission
        """
        pass


if __name__ == '__main__':
    unittest.main()
