# coding: utf-8

"""
    Knetik Platform API Documentation latest 

    This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.

    OpenAPI spec version: latest 
    Contact: support@knetik.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import knetik_cloud
from knetik_cloud.rest import ApiException
from knetik_cloud.models.page_resource_revenue_country_report_resource import PageResourceRevenueCountryReportResource


class TestPageResourceRevenueCountryReportResource(unittest.TestCase):
    """ PageResourceRevenueCountryReportResource unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPageResourceRevenueCountryReportResource(self):
        """
        Test PageResourceRevenueCountryReportResource
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = knetik_cloud.models.page_resource_revenue_country_report_resource.PageResourceRevenueCountryReportResource()
        pass


if __name__ == '__main__':
    unittest.main()
