# coding: utf-8

"""
    Knetik Platform API Documentation Latest

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: Latest
    Contact: support@knetik.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.comment_search import CommentSearch


class TestCommentSearch(unittest.TestCase):
    """ CommentSearch unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommentSearch(self):
        """
        Test CommentSearch
        """
        model = swagger_client.models.comment_search.CommentSearch()


if __name__ == '__main__':
    unittest.main()
