# coding: utf-8

"""
    Knetik Platform API Documentation latest 

    This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com

    OpenAPI spec version: latest 
    Contact: support@knetik.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.forward_log import ForwardLog


class TestForwardLog(unittest.TestCase):
    """ ForwardLog unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testForwardLog(self):
        """
        Test ForwardLog
        """
        model = swagger_client.models.forward_log.ForwardLog()


if __name__ == '__main__':
    unittest.main()
