# coding: utf-8

"""
    Knetik Platform API Documentation latest 

    This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com

    OpenAPI spec version: latest 
    Contact: support@knetik.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.store_subscriptions_api import StoreSubscriptionsApi


class TestStoreSubscriptionsApi(unittest.TestCase):
    """ StoreSubscriptionsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.store_subscriptions_api.StoreSubscriptionsApi()

    def tearDown(self):
        pass

    def test_create_subscription(self):
        """
        Test case for create_subscription

        Creates a subscription item and associated plans
        """
        pass

    def test_create_subscription_template(self):
        """
        Test case for create_subscription_template

        Create a subscription template
        """
        pass

    def test_delete_subscription(self):
        """
        Test case for delete_subscription

        Delete a subscription plan
        """
        pass

    def test_delete_subscription_template(self):
        """
        Test case for delete_subscription_template

        Delete a subscription template
        """
        pass

    def test_get_subscription(self):
        """
        Test case for get_subscription

        Retrieve a single subscription item and associated plans
        """
        pass

    def test_get_subscription_template(self):
        """
        Test case for get_subscription_template

        Get a single subscription template
        """
        pass

    def test_get_subscription_templates(self):
        """
        Test case for get_subscription_templates

        List and search subscription templates
        """
        pass

    def test_get_subscriptions(self):
        """
        Test case for get_subscriptions

        List available subscription items and associated plans
        """
        pass

    def test_process_subscriptions(self):
        """
        Test case for process_subscriptions

        Processes subscriptions and charge dues
        """
        pass

    def test_update_subscription(self):
        """
        Test case for update_subscription

        Updates a subscription item and associated plans
        """
        pass

    def test_update_subscription_template(self):
        """
        Test case for update_subscription_template

        Update a subscription template
        """
        pass


if __name__ == '__main__':
    unittest.main()
