# coding: utf-8

"""
    Knetik Platform API Documentation latest 

    This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.

    OpenAPI spec version: latest 
    Contact: support@knetik.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ActionContextobject(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mapping': 'object',
        'type': 'str'
    }

    attribute_map = {
        'mapping': 'mapping',
        'type': 'type'
    }

    def __init__(self, mapping=None, type=None):
        """
        ActionContextobject - a model defined in Swagger
        """

        self._mapping = None
        self._type = None
        self.discriminator = None

        self.mapping = mapping
        self.type = type

    @property
    def mapping(self):
        """
        Gets the mapping of this ActionContextobject.
        The mapping of the action context

        :return: The mapping of this ActionContextobject.
        :rtype: object
        """
        return self._mapping

    @mapping.setter
    def mapping(self, mapping):
        """
        Sets the mapping of this ActionContextobject.
        The mapping of the action context

        :param mapping: The mapping of this ActionContextobject.
        :type: object
        """
        if mapping is None:
            raise ValueError("Invalid value for `mapping`, must not be `None`")

        self._mapping = mapping

    @property
    def type(self):
        """
        Gets the type of this ActionContextobject.
        The name of the action

        :return: The type of this ActionContextobject.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this ActionContextobject.
        The name of the action

        :param type: The type of this ActionContextobject.
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ActionContextobject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
