# coding: utf-8

"""
    Knetik Platform API Documentation latest 

    This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.

    OpenAPI spec version: latest 
    Contact: support@knetik.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class GuestPlayable(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'allowed': 'bool',
        'leaderboard': 'bool'
    }

    attribute_map = {
        'allowed': 'allowed',
        'leaderboard': 'leaderboard'
    }

    def __init__(self, allowed=None, leaderboard=None):
        """
        GuestPlayable - a model defined in Swagger
        """

        self._allowed = None
        self._leaderboard = None
        self.discriminator = None

        if allowed is not None:
          self.allowed = allowed
        if leaderboard is not None:
          self.leaderboard = leaderboard

    @property
    def allowed(self):
        """
        Gets the allowed of this GuestPlayable.
        Whether guests are allowed to use items

        :return: The allowed of this GuestPlayable.
        :rtype: bool
        """
        return self._allowed

    @allowed.setter
    def allowed(self, allowed):
        """
        Sets the allowed of this GuestPlayable.
        Whether guests are allowed to use items

        :param allowed: The allowed of this GuestPlayable.
        :type: bool
        """

        self._allowed = allowed

    @property
    def leaderboard(self):
        """
        Gets the leaderboard of this GuestPlayable.
        Whether guests are allowed on the leaderboard

        :return: The leaderboard of this GuestPlayable.
        :rtype: bool
        """
        return self._leaderboard

    @leaderboard.setter
    def leaderboard(self, leaderboard):
        """
        Sets the leaderboard of this GuestPlayable.
        Whether guests are allowed on the leaderboard

        :param leaderboard: The leaderboard of this GuestPlayable.
        :type: bool
        """

        self._leaderboard = leaderboard

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, GuestPlayable):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
