# coding: utf-8

"""
    Knetik Platform API Documentation latest 

    This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.

    OpenAPI spec version: latest 
    Contact: support@knetik.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ImportJobOutputResource(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'line_number': 'int'
    }

    attribute_map = {
        'description': 'description',
        'line_number': 'line_number'
    }

    def __init__(self, description=None, line_number=None):
        """
        ImportJobOutputResource - a model defined in Swagger
        """

        self._description = None
        self._line_number = None

        if description is not None:
          self.description = description
        if line_number is not None:
          self.line_number = line_number

    @property
    def description(self):
        """
        Gets the description of this ImportJobOutputResource.
        The description of the import job

        :return: The description of this ImportJobOutputResource.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this ImportJobOutputResource.
        The description of the import job

        :param description: The description of this ImportJobOutputResource.
        :type: str
        """

        self._description = description

    @property
    def line_number(self):
        """
        Gets the line_number of this ImportJobOutputResource.
        The line number of the import job

        :return: The line_number of this ImportJobOutputResource.
        :rtype: int
        """
        return self._line_number

    @line_number.setter
    def line_number(self, line_number):
        """
        Sets the line_number of this ImportJobOutputResource.
        The line number of the import job

        :param line_number: The line_number of this ImportJobOutputResource.
        :type: int
        """

        self._line_number = line_number

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ImportJobOutputResource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
