# coding: utf-8

"""
    Knetik Platform API Documentation latest 

    This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com

    OpenAPI spec version: latest 
    Contact: support@knetik.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ParameterResource(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, of=None, type=None, value=None):
        """
        ParameterResource - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'of': 'str',
            'type': 'str',
            'value': 'object'
        }

        self.attribute_map = {
            'of': 'of',
            'type': 'type',
            'value': 'value'
        }

        self._of = of
        self._type = type
        self._value = value

    @property
    def of(self):
        """
        Gets the of of this ParameterResource.

        :return: The of of this ParameterResource.
        :rtype: str
        """
        return self._of

    @of.setter
    def of(self, of):
        """
        Sets the of of this ParameterResource.

        :param of: The of of this ParameterResource.
        :type: str
        """

        self._of = of

    @property
    def type(self):
        """
        Gets the type of this ParameterResource.

        :return: The type of this ParameterResource.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this ParameterResource.

        :param type: The type of this ParameterResource.
        :type: str
        """

        self._type = type

    @property
    def value(self):
        """
        Gets the value of this ParameterResource.

        :return: The value of this ParameterResource.
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value):
        """
        Sets the value of this ParameterResource.

        :param value: The value of this ParameterResource.
        :type: object
        """

        self._value = value

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ParameterResource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
