# coding: utf-8

"""
    Knetik Platform API Documentation latest 

    This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.

    OpenAPI spec version: latest 
    Contact: support@knetik.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class StateResource(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'country_code_iso3': 'str',
        'id': 'int',
        'name': 'str'
    }

    attribute_map = {
        'code': 'code',
        'country_code_iso3': 'country_code_iso3',
        'id': 'id',
        'name': 'name'
    }

    def __init__(self, code=None, country_code_iso3=None, id=None, name=None):
        """
        StateResource - a model defined in Swagger
        """

        self._code = None
        self._country_code_iso3 = None
        self._id = None
        self._name = None

        if code is not None:
          self.code = code
        if country_code_iso3 is not None:
          self.country_code_iso3 = country_code_iso3
        if id is not None:
          self.id = id
        if name is not None:
          self.name = name

    @property
    def code(self):
        """
        Gets the code of this StateResource.
        The code of the state

        :return: The code of this StateResource.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """
        Sets the code of this StateResource.
        The code of the state

        :param code: The code of this StateResource.
        :type: str
        """

        self._code = code

    @property
    def country_code_iso3(self):
        """
        Gets the country_code_iso3 of this StateResource.
        The iso3 of the country this state is in

        :return: The country_code_iso3 of this StateResource.
        :rtype: str
        """
        return self._country_code_iso3

    @country_code_iso3.setter
    def country_code_iso3(self, country_code_iso3):
        """
        Sets the country_code_iso3 of this StateResource.
        The iso3 of the country this state is in

        :param country_code_iso3: The country_code_iso3 of this StateResource.
        :type: str
        """

        self._country_code_iso3 = country_code_iso3

    @property
    def id(self):
        """
        Gets the id of this StateResource.
        The unique ID for the state

        :return: The id of this StateResource.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this StateResource.
        The unique ID for the state

        :param id: The id of this StateResource.
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this StateResource.
        The name of the state

        :return: The name of this StateResource.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this StateResource.
        The name of the state

        :param name: The name of this StateResource.
        :type: str
        """

        self._name = name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, StateResource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
