# coding: utf-8

"""
    Knetik Platform API Documentation Latest

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: Latest
    Contact: support@knetik.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ActivityOccurrenceCreationFailure(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, user_results=None):
        """
        ActivityOccurrenceCreationFailure - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'user_results': 'list[ActivityOccurrenceJoinResult]'
        }

        self.attribute_map = {
            'user_results': 'user_results'
        }

        self._user_results = user_results

    @property
    def user_results(self):
        """
        Gets the user_results of this ActivityOccurrenceCreationFailure.
        The details of each user's entry, or just the current user's if not run with ACTIVITIES_ADMIN permission

        :return: The user_results of this ActivityOccurrenceCreationFailure.
        :rtype: list[ActivityOccurrenceJoinResult]
        """
        return self._user_results

    @user_results.setter
    def user_results(self, user_results):
        """
        Sets the user_results of this ActivityOccurrenceCreationFailure.
        The details of each user's entry, or just the current user's if not run with ACTIVITIES_ADMIN permission

        :param user_results: The user_results of this ActivityOccurrenceCreationFailure.
        :type: list[ActivityOccurrenceJoinResult]
        """

        self._user_results = user_results

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
